// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtRbZlAZm36439TyaePrR0yL2V1RZ4Ttc',
    appId: '1:129794755303:web:2799e208164b4815037042',
    messagingSenderId: '129794755303',
    projectId: 'central-ips-7213b',
    authDomain: 'central-ips-7213b.firebaseapp.com',
    databaseURL: 'https://central-ips-7213b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'central-ips-7213b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJQzyRVjoBoEffzsvAwR5vdMeNNSDL3yw',
    appId: '1:129794755303:android:76fa46594920fd66037042',
    messagingSenderId: '129794755303',
    projectId: 'central-ips-7213b',
    databaseURL: 'https://central-ips-7213b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'central-ips-7213b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEP506Z2RUCTIcgL4QfzdCV5ph_0O9jPM',
    appId: '1:129794755303:ios:1d317ebe0441e7ee037042',
    messagingSenderId: '129794755303',
    projectId: 'central-ips-7213b',
    databaseURL: 'https://central-ips-7213b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'central-ips-7213b.appspot.com',
    iosClientId: '129794755303-a2nsko8cks6hu2s2s0tfscmm9qvk56eg.apps.googleusercontent.com',
    iosBundleId: 'pt.ips.cm.centralips.centralips',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEP506Z2RUCTIcgL4QfzdCV5ph_0O9jPM',
    appId: '1:129794755303:ios:1d317ebe0441e7ee037042',
    messagingSenderId: '129794755303',
    projectId: 'central-ips-7213b',
    databaseURL: 'https://central-ips-7213b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'central-ips-7213b.appspot.com',
    iosClientId: '129794755303-a2nsko8cks6hu2s2s0tfscmm9qvk56eg.apps.googleusercontent.com',
    iosBundleId: 'pt.ips.cm.centralips.centralips',
  );
}
